"""One-time translation on the isolated English branch; removed after application."""
from pathlib import Path

pairs = {
'FightingICEの戦闘、MaleCNS接続データ上の神経シミュレーション、FlyBodyの物理的な身体運動を観測する。評価録画と検証済みLIVEは明確に区別しています。': 'Observe FightingICE combat, neural simulation on MaleCNS connectivity, and physical FlyBody motion. Recorded evaluations and verified LIVE observations are clearly distinguished.',
'評価データを取得できません': 'Evaluation data unavailable',
'結果未記録': 'Result not recorded',
'評価録画': 'recorded evaluation',
'動画を読み込めませんでした': 'Video could not be loaded',
'評価動画を待機中': 'Awaiting an evaluation video',
'公開アセットの接続を確認してください。': 'Check the connection to the published asset.',
'完了済みの評価が公開されると表示します。': 'A completed evaluation will appear here after publication.',
'動画を再読込み': 'Reload video',
'FINAL RESULT / 最終結果': 'FINAL RESULT',
'最終HPは録画の最終結果です。再生中のHPや時刻を表しません。': 'HP values describe the final recorded result, not the current playback frame.',
'評価世代を切替': 'Select evaluation generation',
'最新完了 Gen': 'Latest completed Gen',
'前回 Gen': 'Previous Gen',
'履歴更新を再開': 'Resume history updates',
'履歴更新を停止': 'Pause history updates',
'LIVE観測へ': 'Observe LIVE',
'評価APIを取得できません': 'Evaluation API unavailable',
'。表示がある場合は最終取得時の記録です。': '. Any displayed records are from the last successful fetch.',
'履歴の自動更新を停止中。動画はプレイヤーの再生・停止操作で制御できます。': 'History updates are paused. Use the video player controls to play or pause the recording.',
'CandidateはGen': 'Candidate is now Gen',
'に更新済み。ここに表示する最新完了評価はGen': ' . The latest completed evaluation shown here is Gen',
'です。新世代の評価完了はまだ確認できていません。': '. Completion of the newer evaluation has not yet been verified.',
'いまの行動と、これまでの変化。': 'Current behavior. Recorded progress.',
'自動昇格なし': 'no automatic promotion',
'研究用checkpointの更新': 'Research checkpoint update',
'累積matches': 'Completed matches',
'変更された結合': 'Changed connections',
'最新の完了済み固定条件評価': 'Latest completed fixed-condition evaluation',
'前回完了世代': 'Previous evaluated generation',
'評価ラウンド数': 'Evaluation rounds',
'Candidateと承認済み推論を分離': 'Candidates remain separate from approved inference',
'自動昇格': 'Automatic promotion',
'世代数や結合の変化だけでは、学習効果や性能向上を証明できません。': 'Generation counts and changed connections alone do not demonstrate learning effectiveness or improved performance.',
'明示的な評価・承認が必要': 'Explicit evaluation and approval required',
'評価条件・checkpointの記録を開く': 'Inspect evaluation and checkpoint records',
'選択中の評価': 'Selected evaluation',
'未記録': 'Not recorded',
'報酬の設定変更はこの画面から行いません。異なる評価条件を同一条件の比較として扱いません。': 'This viewer does not change reward settings. Evaluations with different protocols are not presented as matched comparisons.',
'LIVE表示を再開': 'Resume LIVE display',
'表示更新を停止': 'Pause display updates',
'発火上位のbody ID': 'Top-spiking body IDs',
'上位bodyの記録なし': 'No top-body records',
'運動出力の記録なし': 'No motor-output records',
'運動出力': 'Motor output',
'受信元の経過': 'Source age',
'上位標本のみ。全神経の活動分布ではありません。': 'Top-body sample only, not an all-neuron activity distribution.',
'神経活動は未収録': 'Neural activity not recorded',
'神経入力を待機中': 'Awaiting neural input',
'この評価動画に同期した神経記録はありません。LIVE観測で表示します。': 'This video has no synchronized neural recording. Verified neural activity is shown in the LIVE view.',
'検証済みの入力を受信したときだけ表示します。': 'Displayed only after verified input is received.',
'実接続データ上のシミュレーション': 'Simulation on biological connectivity',
'身体で、読む。': 'Read the body.',
'身体記録は未収録': 'Body motion not recorded',
'物理レンダー待機中': 'Awaiting physical render',
'録画に別時刻の身体を重ねません。': 'Body frames from another time are not overlaid on recordings.',
'神経入力とPNGの整合確認後に表示。': 'Displayed after verifying neural-input and PNG consistency.',
'正規化指令 0–1 · 生理学的な筋活動量ではありません。': 'Normalized command, 0–1. Not a physiological measure of muscle activity.',
'保持入力': 'Held input',
'破棄した実時間': 'Dropped wall time',
'THE EXPERIMENT / 観測の境界': 'THE EXPERIMENT / INTERPRETATION BOUNDARIES',
'本物の構造。': 'Real structure.',
'明示された仮定。': 'Explicit assumptions.',
'見るためのデータと、行動を決める入力を分ける。': 'Spectator data is separate from policy input.',
'解剖学と神経活動': 'Anatomy and neural activity',
'MaleCNSの接続データにShiu LIFモデルを適用した神経活動です。生きたハエからの活動実測でも、全脳活動の可視化でもありません。上位body IDの標本を表示します。': 'Neural activity is simulated by applying the Shiu LIF model to MaleCNS connectivity. It is neither activity recorded from a living fly nor a whole-brain activity map. The viewer displays a bounded sample of top body IDs.',
'神経からゲーム・身体へ': 'From neural activity to game and body',
'ゲーム入出力とMaleCNS→FlyBody actuatorの変換はプロジェクト定義です。生物学的に同定された筋支配地図ではありません。FightingICEの位置をコピーしてハエを動かすことはしません。': 'Game input/output and the MaleCNS-to-FlyBody actuator mapping are project-defined interfaces, not an experimentally identified muscle-innervation map. FightingICE coordinates do not position the fly.',
'時刻と画像の対応': 'Time and image correspondence',
'LIVEでは神経活動・身体の保持入力を、実際に観測したdecision履歴に照合し、身体PNGをSHA-256で検証します。戦闘ScreenDataは独立に取得され、画像の厳密なframe同期は主張しません。負荷時に物理時間が遅れることがあります。': 'LIVE neural activity and held body input are matched to observed decision history, and body PNG bytes are verified by SHA-256. FightingICE ScreenData is sampled independently; exact image-frame synchronization is not claimed. Physics can run slower than wall time under load.',
'出典・実行状態を開く': 'Inspect provenance and runtime state',
'観測はread-only。画素はpolicy入力に使いません。': 'Observation is read-only. Pixels are not policy inputs.',
'この画面には検証済みLIVE snapshotはありません。': 'No verified LIVE snapshot is available in this view.',
'観測画面へスキップ': 'Skip to the observatory',
'Connectome Fighter ホーム': 'Connectome Fighter home',
'メインナビゲーション': 'Main navigation',
'LIVE観測': 'LIVE observatory',
'実験について': 'About the experiment',
'戦う。その内側を、観る。': 'Watch the fight. See the circuitry.',
'ゲームの行動と、神経活動から動くショウジョウバエの身体を観測する。': 'Observe fighting-game behavior and a fruit-fly body driven by neural activity.',
'録画評価 · LIVEではありません': 'Recorded evaluation · not LIVE',
'観測専用 · 学習更新なし': 'Read-only observation · no learning updates',
'loopback上の実runtimeです。本番Vercelの稼働証明ではありません。': 'actual runtime on loopback, not evidence of Vercel production compute.',
'LIVE計算は利用枠の上限で停止しています。': 'LIVE compute is paused by the provider usage limit.',
'接続がない状態を録画や擬似活動で置き換えません。': 'A disconnected stream is not replaced with a recording or simulated display data.',
'評価録画を見る': 'Watch recorded evaluations',
'表示更新を停止しました。再開時には最新の検証済み入力を取得します。サーバーの計算は操作しません。': 'Display updates are paused. Resuming fetches the latest verified input; it does not control server computation.',
'戦闘と両側の神経活動': 'Combat and neural activity for both fighters',
'計算リソース待ち': 'Awaiting compute capacity',
'表示を一時停止': 'Display paused',
'検証済みの戦闘を待機中': 'Awaiting verified combat data',
'この領域には実FightingICEのScreenDataだけを表示します。': 'Only actual FightingICE ScreenData is displayed in this area.',
'評価動画とLIVE神経観測は別の記録です。録画に未収録の活動は生成しません。': 'Recorded evaluations and LIVE neural observations are separate records. Unrecorded activity is not invented for a video.',
'戦闘画像は独立サンプリング。神経・身体は実観測履歴の保持入力に照合しています。': 'Combat images are independently sampled. Neural and body panels match held input to observed decision history.',
'プロジェクト定義の情報経路': 'Project-defined information path',
'設計上の接続 · 生物学的因果の証明ではない': 'Designed connections, not proof of biological causation',
'ゲーム観測': 'Game observation',
'感覚入力': 'Sensory input',
'ゲームaction': 'Game action',
'同じ神経活動、もうひとつの身体。': 'One neural signal. Another body.',
'FightingICEとは独立した、実MuJoCo物理。': 'Actual MuJoCo physics, independent of FightingICE.',
'行動の記録': 'Observed actions',
'この閲覧中の直近8記録 · 欠落なしのreplayではない': 'Last 8 observations in this visit · not lossless replay',
'検証済みの観測記録が得られるまで、タイムラインを描画しません。': 'The timeline appears only after verified observations are available.',
'Candidateの更新・評価履歴へ': 'Candidate updates and evaluation history',
'神経活動': 'neural activity',
'骨格表示はMaleCNS v1.0が公開する実ニューロンcenterline SWC（MaleCNS EM座標、8 nm単位）のうち、そのclipで最も発火したbodyを後解析で選んだX–Z投影です。明るさは現在時刻のspike活動に対応します。表示データは方策入力に使いません。下のsomaNeuromere集計も併記します。': 'Skeletons are X–Z projections of released MaleCNS v1.0 neuron-centerline SWCs (MaleCNS EM coordinates, units of 8 nm). Bodies with the most spikes in each clip are selected post hoc. Brightness represents activity at the displayed time. Display data is not policy input. The somaNeuromere aggregates are also shown below.',
'FightingICE の x/y/action を FlyBody の位置やposeにコピーしません': 'FightingICE x/y/action values do not position the FlyBody body',
'FightingICE x/y/actionをFlyBodyのposition/poseへコピーしません': 'FightingICE x/y/action does not position or pose the physical FlyBody',
}
for name in ['app/layout.tsx','app/live-client.tsx','app/live/arena-client.tsx','app/observatory.tsx','scripts/test_observatory_design.mjs','scripts/validate_public_surface_contract.py','spectator/index.html']:
    p=Path(name); text=p.read_text()
    for old,new in sorted(pairs.items(),key=lambda item:-len(item[0])): text=text.replace(old,new)
    text=text.replace('lang="ja"','lang="en"').replace("'ja-JP'","'en-GB'")
    text=text.replace('Candidate is now Gen 10に更新済み','Candidate is now Gen 10')
    p.write_text(text)
p=Path('tests/test_flybody_publisher_contract.py'); text=p.read_text().replace('テスト',r'\u30c6\u30b9\u30c8').replace('テ',r'\u30c6'); p.write_text(text)
Path('README.ja.md').write_text(Path('README.md').read_text())
for name in ['PUBLIC_SURFACE_SPLIT','LIVE_PUBLICATION_GATE']:
    Path(f'docs/{name}.ja.md').write_text(Path(f'docs/{name}.md').read_text())
for name in ['app/layout.tsx','site/index.html','spectator/index.html']:
    p=Path(name); p.write_text(p.read_text().replace('lang="ja"','lang="en"'))
p=Path('scripts/test_observatory_design.mjs'); p.write_text(p.read_text().replace('await page.goto(base);','await page.goto(base); assert.equal(await page.locator("html").getAttribute("lang"), "en");'))
p=Path('scripts/validate_public_surface_contract.py'); text=p.read_text().replace('require("app/live-client.tsx", "MODEL ROUND EVALUATION", "candidate only", "policy_pixel_access=false")', 'require("app/live-client.tsx", "FROZEN EVALUATION", "candidate only", "policy_pixel_access=false", \'mode="replay"\')')
old='''    require("app/live/arena-client.tsx", "Official FightingICE ScreenData", FLYBODY_COMMIT,
            FLYBODY_ADAPTER, "SHA-256", "Awaiting aligned fresh input", "verified-held-input",
            "No synthetic fight, recorded LIVE, SVG fly or cached pose is substituted",
            "not an identified biological muscle innervation map")'''
new='''    require("app/live/arena-client.tsx", FLYBODY_COMMIT, FLYBODY_ADAPTER,
            "SHA-256", "Awaiting aligned fresh input", "verified-held-input", 'mode="live"')
    require("app/observatory.tsx", "Official FightingICE screen", "RECORDED EVALUATION",
            "No verified LIVE snapshot", "SHA-256", "project-defined interfaces",
            "not an experimentally identified muscle-innervation map")'''
assert old in text
p.write_text(text.replace(old,new))
