"""Durable, checksummed checkpoint format for character-specific brain lineages."""
from __future__ import annotations

from pathlib import Path
import hashlib
import os
import random
from typing import Any

import numpy as np
import torch

from .characters import lineage_id, validate_character

CHECKPOINT_SCHEMA = 1


def sha256_file(path: str | Path) -> str:
    h = hashlib.sha256()
    with Path(path).open("rb") as f:
        for block in iter(lambda: f.read(1024 * 1024), b""):
            h.update(block)
    return h.hexdigest()


def checkpoint_filename(character: str) -> str:
    return f"brain-{validate_character(character)}.pt"


def checkpoint_id(character: str, generation: int) -> str:
    return f"{validate_character(character).lower()}-g{int(generation):06d}"


def save_checkpoint(
    path: str | Path,
    *,
    character: str,
    actor: torch.nn.Module,
    critic: torch.nn.Module,
    optimizer: torch.optim.Optimizer,
    generation: int,
    training_matches: int,
    updates: int,
    graph_hash: str,
    routing_hash: str,
    code_sha: str,
    hyperparameters: dict[str, Any],
) -> dict[str, Any]:
    character = validate_character(character)
    if generation < 0 or training_matches < 0 or updates < 0:
        raise ValueError("Checkpoint counters must be non-negative")
    if not graph_hash or not routing_hash:
        raise ValueError("Graph and routing hashes are required")
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    metadata = {
        "schema_version": CHECKPOINT_SCHEMA,
        "character": character,
        "lineage_id": lineage_id(character),
        "checkpoint_id": checkpoint_id(character, generation),
        "generation": int(generation),
        "training_matches": int(training_matches),
        "updates": int(updates),
        "graph_hash": graph_hash,
        "routing_hash": routing_hash,
        "code_sha": str(code_sha or "unknown"),
        "hyperparameters": dict(hyperparameters),
    }
    payload = {
        "metadata": metadata,
        "actor_state": actor.state_dict(),
        "critic_state": critic.state_dict(),
        "optimizer_state": optimizer.state_dict(),
        "rng": {
            "python": random.getstate(),
            "numpy": np.random.get_state(),
            "torch": torch.get_rng_state(),
        },
    }
    tmp = path.with_suffix(path.suffix + ".tmp")
    torch.save(payload, tmp)
    os.replace(tmp, path)
    digest = sha256_file(path)
    path.with_suffix(path.suffix + ".sha256").write_text(f"{digest}  {path.name}\n", encoding="utf-8")
    metadata = dict(metadata)
    metadata["sha256"] = digest
    return metadata


def load_checkpoint(
    path: str | Path,
    *,
    expected_character: str | None = None,
    expected_graph_hash: str | None = None,
    expected_routing_hash: str | None = None,
    verify_checksum: bool = True,
) -> dict[str, Any]:
    path = Path(path)
    if not path.is_file():
        raise FileNotFoundError(path)
    if verify_checksum:
        sidecar = path.with_suffix(path.suffix + ".sha256")
        if not sidecar.is_file():
            raise ValueError(f"Missing checkpoint checksum: {sidecar}")
        expected_digest = sidecar.read_text(encoding="utf-8").strip().split()[0]
        actual_digest = sha256_file(path)
        if expected_digest != actual_digest:
            raise ValueError("Checkpoint checksum mismatch")
    # Checkpoints are generated by this repository and stored as controlled
    # release assets. Optimizer/RNG state requires full torch serialization.
    payload = torch.load(path, map_location="cpu", weights_only=False)
    metadata = payload.get("metadata", {})
    if metadata.get("schema_version") != CHECKPOINT_SCHEMA:
        raise ValueError("Unsupported checkpoint schema")
    character = validate_character(metadata.get("character", ""))
    if expected_character is not None and character != validate_character(expected_character):
        raise ValueError("Checkpoint belongs to another character")
    if expected_graph_hash is not None and metadata.get("graph_hash") != expected_graph_hash:
        raise ValueError("Checkpoint graph hash mismatch")
    if expected_routing_hash is not None and metadata.get("routing_hash") != expected_routing_hash:
        raise ValueError("Checkpoint routing hash mismatch")
    if metadata.get("lineage_id") != lineage_id(character):
        raise ValueError("Checkpoint lineage mismatch")
    return payload


def restore_rng(payload: dict[str, Any]) -> None:
    rng = payload.get("rng", {})
    if "python" in rng:
        random.setstate(rng["python"])
    if "numpy" in rng:
        np.random.set_state(rng["numpy"])
    if "torch" in rng:
        torch.set_rng_state(rng["torch"])
